name: .NET Continuous Integration

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test Project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Run tests
      run: dotnet test --logger GitHubActions ./src/CelesTrakSdk.sln
